root <- normalizePath(".", winslash = "/", mustWork = TRUE)

copy_dir <- function(from, to) {
  if (!dir.exists(from)) {
    return(FALSE)
  }
  if (dir.exists(to)) {
    unlink(to, recursive = TRUE, force = TRUE)
  }
  dir.create(dirname(to), recursive = TRUE, showWarnings = FALSE)
  ok <- file.copy(from, dirname(to), recursive = TRUE, copy.date = TRUE)
  if (!isTRUE(ok)) {
    stop("failed to stage directory: ", from, call. = FALSE)
  }
  TRUE
}

inst_modules <- file.path(root, "inst", "modules")
sources <- list(
  hannanum = list(
    from = file.path(root, "src", "modules", "hannanum", "inst", "hannanum-data"),
    to = file.path(inst_modules, "hannanum", "inst", "hannanum-data")
  )
)

available <- vapply(sources, function(x) dir.exists(x$from), logical(1))
if (!any(available)) {
  if (!dir.exists(inst_modules)) {
    stop("neither source modules nor staged inst/modules are available", call. = FALSE)
  }
  quit(save = "no")
}

unlink(inst_modules, recursive = TRUE, force = TRUE)
for (source in sources[available]) {
  copy_dir(source$from, source$to)
}
writeLines("generated by configure", file.path(inst_modules, ".hannlp-generated"))
